apiVersion: v1
kind: Pod
metadata:
  name: bot-pod
spec:
  containers:
    - name: watson-recipe-bot
      image: markwatsonatx/watson-recipe-bot-python-cloudant:latest
      env:
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: slackBotToken
        - name: SLACK_BOT_ID
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: slackBotId
        - name: SPOONACULAR_KEY
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: spoonacularKey
        - name: CONVERSATION_USERNAME
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: conversationUsername
        - name: CONVERSATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: conversationPassword
        - name: CONVERSATION_WORKSPACE_ID
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: conversationWorkspaceId
        - name: CLOUDANT_USERNAME
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: cloudantUsername
        - name: CLOUDANT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: cloudantPassword
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: cloudantUrl
        - name: CLOUDANT_DB_NAME
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: cloudantDbName